# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerroomtv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('web_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('thumbnail_url', models.URLField()),
                ('featured_recordings', models.ManyToManyField(related_name='featured_in_channels', to='boilerroomtv.Recording')),
            ],
        ),
    ]
