# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerroomtv', '0003_auto_20170925_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('web_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='genres',
            field=models.ManyToManyField(related_name='recordings', to='boilerroomtv.Genre'),
        ),
    ]
